openapi: 3.0.0
info:
  title: Critica API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/lobby/create:
    post:
      summary: Create Lobby
      description: Create Lobby
      operationId: createLobby
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLobby'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/get/{id}:
    get:
      summary: Get Lobby
      description: Get Lobby
      operationId: getLobby
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/list:
    get:
      summary: List Lobbies
      description: List Lobbies
      operationId: listLobbies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/delete/{id}:
    delete:
      summary: Delete Lobby
      description: Delete Lobby
      operationId: deleteLobby
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    CreateLobby:
        type: object
        properties:
            date:
              type: string
            name:
              type: string
    Lobby:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        game:
          type: array
          items:
              type: string
        host:
          type: string
        players:
          type: array
          items:
            type: string
        maxPlayers:
          type: integer
          default: 10
        isPrivate:
          type: boolean
        password:
          type: string
          nullable: true
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UpdateGame:
        type: object
        properties:
            id:
              type: integer
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        isAdmin:
          type: boolean
    Game:
      type: object
      properties:
        id:
          type:
            integer
    InternalServerError:
      type: object
      properties:
        message:
          type: "Server error occurred"
    Unauthorized:
        type: object
        properties:
            message:
            type: "You're not logged in"
