openapi: 3.0.0
info:
  title: Critica API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/lobby/create:
    post:
      summary: Create Lobby
      description: Create Lobby
      operationId: createLobby
      tags:
        - Lobby
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLobby'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/get/{id}:
    get:
      summary: Get Lobby
      description: Get Lobby
      operationId: getLobby
      tags:
        - Lobby
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/list:
    get:
      summary: List Lobbies
      description: List Lobbies
      operationId: listLobbies
      tags:
        - Lobby
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LobbyList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/delete/{id}:
    delete:
      summary: Delete Lobby
      description: Delete Lobby
      operationId: deleteLobby
      tags:
        - Lobby
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/addGame:
    post:
      summary: Add Game to Lobby
      description: Add Game
      operationId: addGame
      tags:
        - Lobby
        - Game
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
        - name: time
          in: query
          description: Time of the game
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/addPlayer/{playerId}:
    post:
      summary: Add Player by ID to Lobby
      description: Add Player
      operationId: addPlayer
      tags:
        - Lobby
        - User
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
        - name: playerId
          in: path
          description: Player ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/removePlayer:
    patch:
      summary: Remove Player from Lobby
      description: Remove Player
      operationId: removePlayer
      tags:
        - Lobby
        - User
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
        - name: playerName
          in: query
          description: Player Name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/removePlayer/{playerId}:
    patch:
      summary: Remove Player by ID from Lobby
      description: Remove Player
      operationId: removePlayer
      tags:
        - Lobby
        - User
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
        - name: playerId
          in: path
          description: Player ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lobby'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/players:
    get:
      summary: Get Players in Lobby
      description: Get Players
      operationId: getPlayers
      tags:
        - Lobby
        - Player
        - User
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/lobby/{id}/games:
    get:
      summary: Get Games in Lobby
      description: Get Games
      operationId: getGames
      tags:
        - Lobby
        - Game
      parameters:
        - name: id
          in: path
          description: Lobby ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    CreateLobby:
        type: object
        properties:
            date:
              type: string
            name:
              type: string
    Lobby:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        games:
          type: array
          items:
              type: string
        creator:
          type: integer
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
    LobbyList:
        type: object
        properties:
            lobbies:
            type: array
            items:
                $ref: '#/components/schemas/Lobby'
    Game:
      type: object
      properties:
        id:
          type:
            integer
        date:
          type: string
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        currentStage:
          type: object
          $ref: '#/components/schemas/Stage'
          nullable: true
        nominates:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        votes:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        mafiaShot:
          type: integer
        detectiveCheck:
          type: integer
        donCheck:
          type: integer
        playersEliminated:
          type: array
          items:
            $ref: '#/components/schemas/Player'
    GameList:
        type: object
        properties:
            games:
            type: array
            items:
                $ref: '#/components/schemas/Game'
    Player:
        type: object
        properties:
            id:
              type: integer
            name:
              type: string
            alive:
              type: boolean
            inGame:
              type: boolean
            bonusPoints:
              type: integer
    PlayerList:
        type: object
        properties:
            players:
            type: array
            items:
                $ref: '#/components/schemas/Player'
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UpdateGame:
        type: object
        properties:
            id:
              type: integer
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        isAdmin:
          type: boolean

    InternalServerError:
      type: object
      properties:
        message:
          type: string
          example: "Server error occurred"
    Unauthorized:
        type: object
        properties:
            message:
              type: string
              example: "You're not logged in"
