ktor:
  deployment:
    port: 8080
    sslPort: 8443
  application:
    modules: [com.critica.ApplicationKt.module]
  database:
    url: db-postgresql-ams3-critica-do-user-7276549-0.b.db.ondigitalocean.com:25060/critica_db
    username: doadmin
    password: AVNS_rncUe4QF-nJGbERNe48
    driver-class-name: org.postgresql.Driver
  jwt:
    secret: secret
    expiration: 86400000
    realm: JWT
    audience: http://localhost:8080
    issuer: http://localhost:8080
  oauth:
    client:
      id: "google"
      secret: "secret"
    token:
      url: https://oauth2.googleapis.com/token
    auth:
      url: https://accounts.google.com/o/oauth2/v2/auth
    jwkset:
      url: https://www.googleapis.com/oauth2/v3/certs
    redirect:
      url: http://localhost:8080/login/oauth2/code/google